const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const observer=new IntersectionObserver((entries)=>{entries.forEach((e)=>{if(e.isIntersecting){const el=e.target;el.classList.add('in');observer.unobserve(el);if(el.classList.contains('reveal')){const done=ev=>{if(ev.target!==el||ev.propertyName!=='transform')return;el.removeEventListener('transitionend',done);el.style.transitionDelay='';el.classList.remove('reveal','scale','in')};el.addEventListener('transitionend',done)}}})},{threshold:.08,rootMargin:'0px 0px -8%'});$$('.reveal').forEach(el=>observer.observe(el));
const nav=$('.nav-links'), toggle=$('.menu-toggle');toggle?.addEventListener('click',()=>nav.classList.toggle('open'));$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const navItems=$$('.nav-links a');const sections=$$('[data-nav]');const spy=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){const id=e.target.dataset.nav;navItems.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${id}`))}})},{rootMargin:'-35% 0px -55%',threshold:0});sections.forEach(s=>spy.observe(s));
const art=$('.hero-art'), tilt=$('.tilt');let tx=0,ty=0,cx=0,cy=0;art?.addEventListener('pointermove',e=>{const r=art.getBoundingClientRect();tx=((e.clientX-r.left)/r.width-.5)*12;ty=((e.clientY-r.top)/r.height-.5)*-10});art?.addEventListener('pointerleave',()=>{tx=ty=0});(function animate(){cx+=(tx-cx)*.06;cy+=(ty-cy)*.06;if(tilt)tilt.style.transform=`perspective(1100px) rotateY(${cx}deg) rotateX(${cy}deg)`;requestAnimationFrame(animate)})();
const modal=$('.modal');$('[data-modal-open]')?.addEventListener('click',()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'});function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}$('.modal-close')?.addEventListener('click',closeModal);$('.modal-backdrop')?.addEventListener('click',closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
$('.newsletter')?.addEventListener('submit',e=>{e.preventDefault();const btn=$('button',e.currentTarget);const old=btn.textContent;btn.textContent='✓';setTimeout(()=>btn.textContent=old,1800);e.currentTarget.reset()});
const stars=$('.hero-stars');if(stars){const frag=document.createDocumentFragment();for(let i=0;i<110;i++){const s=document.createElement('span');const size=Math.random()*2.2+.8;s.className=Math.random()<.18?'star green':'star';s.style.cssText=`left:${Math.random()*100}%;top:${Math.random()*100}%;width:${size}px;height:${size}px;--d:${(Math.random()*4+2).toFixed(2)}s;--delay:${(Math.random()*-6).toFixed(2)}s`;frag.appendChild(s)}for(let i=0;i<3;i++){const s=document.createElement('span');s.className='shooting-star';s.style.cssText=`left:${55+Math.random()*45}%;top:${Math.random()*40}%;--d:${(Math.random()*6+8).toFixed(2)}s;--delay:${(i*3.5+Math.random()*2).toFixed(2)}s`;frag.appendChild(s)}stars.appendChild(frag)}
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches, finePointer=matchMedia('(pointer: fine)').matches;
const progress=document.createElement('div');progress.className='scroll-progress';document.body.appendChild(progress);const header=$('.header');let scrollTick=false;const onScroll=()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max>0?scrollY/max:0})`;header?.classList.toggle('scrolled',scrollY>30);scrollTick=false};addEventListener('scroll',()=>{if(!scrollTick){scrollTick=true;requestAnimationFrame(onScroll)}},{passive:true});onScroll();
$$('.services-grid,.process-row,.projects-grid,.why-cards,.quotes').forEach(g=>[...g.children].forEach((el,i)=>{if(!el.classList.contains('reveal'))return;el.style.transitionDelay=`${i*90}ms`;el.addEventListener('transitionend',()=>{el.style.transitionDelay=''},{once:true})}));
const processRow=$('.process-row');if(processRow)observer.observe(processRow);
if(!reduceMotion){const counter=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;counter.unobserve(e.target);const el=e.target,m=el.textContent.match(/^(\d+)(.*)$/);if(!m)return;const end=+m[1],suffix=m[2],t0=performance.now(),dur=1800;(function step(t){const p=Math.min((t-t0)/dur,1);el.textContent=Math.round(end*(1-Math.pow(1-p,3)))+suffix;if(p<1)requestAnimationFrame(step)})(t0)}),{threshold:.6});$$('.stats strong').forEach(el=>counter.observe(el))}
$$('.card,.step,.mini-card,.quote,.stats>div').forEach(el=>el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.setProperty('--mx',`${e.clientX-r.left}px`);el.style.setProperty('--my',`${e.clientY-r.top}px`)}));
if(finePointer&&!reduceMotion){$$('.btn.solid,.btn.ghost-glow').forEach(b=>{b.classList.add('magnetic');b.addEventListener('pointermove',e=>{const r=b.getBoundingClientRect();b.style.translate=`${(e.clientX-r.left-r.width/2)*.25}px ${(e.clientY-r.top-r.height/2)*.35}px`});b.addEventListener('pointerleave',()=>{b.style.translate=''})});const glow=document.createElement('div');glow.className='cursor-glow';document.body.appendChild(glow);let gx=innerWidth/2,gy=innerHeight/2,px=gx,py=gy;addEventListener('pointermove',e=>{gx=e.clientX;gy=e.clientY;glow.classList.add('on')},{passive:true});document.addEventListener('pointerleave',()=>glow.classList.remove('on'));(function follow(){px+=(gx-px)*.12;py+=(gy-py)*.12;glow.style.transform=`translate(${px}px,${py}px)`;requestAnimationFrame(follow)})()}
